config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true, uniqueness: true
  validates :price_per_night, presence: true, numericality: true
  validates :number_of_guests, presence: true, numericality: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController

  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new
    end
  end

  def edit
    @flat = Flat.find(params[:id])
  end

  def update
    @flat = Flat.find(params[:id])
    if @flat.update(flat_params)
      redirect_to flat_path(@flat)
    else
      render :edit
    end
  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.destroy
    redirect_to flats_path
  end

  private
  def flat_params
    params.require(:flat).permit(:name, :address, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= simple_form_for(flat) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.submit %>
<% end %>

app/views/flats/edit.html.erb
<div class="container">
  <%= render "form", flat: @flat %>
</div>

app/views/flats/index.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-12">
      <h1>All our Flats</h1>
    </div>
  </div>

  <div class="row">
    <div class="col">
        <p>All <%=@flats.length%> flats.</p>
    </div>
  </div>

  <div class="row row-cols-1 row-cols-md-3">
      <%@flats.each do |flat|%>
          <div class="col mb-4">
            <div class="card h-100">
              <img src="https://source.unsplash.com/featured?home" class="card-img-top" alt="...">
              <div class="card-body bg-light align-items-center">
                <h3 class="card-title"><%=flat.name%></h3>
                <p class="card-text"><%=flat.address%></p>
                <div class="card-text-align">
                  <i class="fas fa-user-friends pr-2"><span class="mb-4"><%=flat.number_of_guests%></span></i>
                  <i class="fas fa-euro-sign ml-2"><%=flat.price_per_night%></i>
                </div>
              </div>
              <div class="card-footer">
                <a href="/flats/<%=flat.id%>" class="card-link">More info</a>
                <a class="ml-3 text-warning card-link" href="/flats/<%=flat.id%>/edit">Edit</a>
                <a data-confirm="Are you sure?" class="ml-3 text-danger card-link" rel="nofollow" data-method="delete" href="/flats/<%=flat.id%>">Remove</a>
              </div>
            </div>
          </div>
      <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<div class="container">
  <%= render "form", flat: @flat %>
</div>

app/views/flats/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('https://source.unsplash.com/featured?home');">
</div>

<div class="container margin-top-negative">
  <div class="row">
    <div class="col-8">
      <div class="card mt-5">
        <div class="card-body">
          <h1 class="card-title"><%=@flat.name%></h1>
          <p class="card-text"><%=@flat.address%></p>
        </div>
      </div>
    </div>
    <div class="col-8">
      <div class="card mt-5">
        <div class="card-body">
          <h3 class="card-title">A bit more about this flat...</h3>
          <p class="card-text"><%=@flat.description%></p>
        </div>
      </div>
    </div>
  </div>

    <div class="col-4 mt-3">
      <div class="card">
        <h4 class="card-title ml-3 mt-4">Book this place!</h4>
        <div class="card-body">
        <form>
          <div class="form-group">
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text" id="basic-addon1">From:</span>
              </div>
              <input type="text" class="form-control" placeholder="12/10/2020" aria-label="Username" aria-describedby="basic-addon1">
            </div>
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text" id="basic-addon1">To:</span>
              </div>
              <input type="text" class="form-control" placeholder="18/10/2020" aria-label="Username" aria-describedby="basic-addon1">
            </div>
            <button type="submit" class="btn btn-success btn-block">Book</button>
          </div>
        </form>
        </div>
      </div>
    </div>

      <div class="card">
        <h3>Details</h3>
        <div class="flex">
          <div class="flex">
            <i class="fas fa-user-friends mr-2"><span><%=@flat.number_of_guests%></span></i>
          </div>
          <div class="flex ml-3">
            <i class="fas fa-euro-sign mr-2"><%=@flat.price_per_night%></i>
          </div>
        </div>
      </div>
      <div class="card">
        <div class="flex-align">
          <h6 class="no-mb">Share</h6>

          <div class="flex">
            <i class="fab fa-facebook-square fa-2x mr-2"></i>
            <i class="fab fa-twitter-square fa-2x mr-2"></i>
            <i class="fab fa-pinterest-square fa-2x mr-2"></i>
            <i class="fas fa-envelope-square fa-2x"></i>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <%= link_to "Simple Airbnb", flats_path, class: "navbar-brand" %>

      <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          <!-- <li class="nav-item active">
            <a class="nav-link" href="./flats">Home <span class="sr-only">(current)</span></a>
          </li> -->
          <li class="nav-item">
            <%= link_to "Add Flat", new_flat_path, class: "nav-link" %>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

    <%= yield %>
  </body>
</html>